### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Dlelo**
Hey guys Kindly help me improve my app. Your comments and feedback will be truly appreciated

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Dlelo** [comment]
Merging the branch develop to Master

**Comment by Dlelo** [comment]
Done with merging develop branch to master branch

**Comment by Dlelo** [comment]
@mwamodojnr  Thank you for reviewing my code!

**Comment by Dlelo** [comment]
@mwamodojnr  Though having problems displaying my shopping list items in the respective shopping list sessions! Any suggestions???

**Pull request merged**
